apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench
  namespace: security-scan
spec:
  template:
    spec:
      hostPID: false 
      automountServiceAccountToken: false
      serviceAccountName: kube-bench
      restartPolicy: Never
      containers:
        - name: kube-bench
          image: ghcr.io/aquasecurity/kube-bench:latest
          command: ["kube-bench", "--json"]
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
