apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench
  namespace: security-scan
spec:
  template:
    spec:
      hostPID: false
      automountServiceAccountToken: true
      serviceAccountName: kube-bench
      restartPolicy: Never
      containers:
        - name: kube-bench
          image: docker.io/aquasec/kube-bench:latest
          command: ["kube-bench", "--json"]
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
