apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sReadonlyRootFS
metadata:
  name: readonly-rootfs
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
