apiVersion: batch/v1
kind: Job
metadata:
  name: delay-gatekeeper-crd
  namespace: gatekeeper-system
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/component: gatekeeper
    app.kubernetes.io/part-of: full-security

spec:
  template:
    spec:
      containers:
        - name: sleeper
          image: busybox
          command: ["sleep", "15"]
      restartPolicy: Never
