apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-gatekeeper-crd
  namespace: gatekeeper-system
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - name: sleeper
          image: busybox
          command: ["sh", "-c", "echo waiting... && sleep 15"]
      restartPolicy: Never
