apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-template-registration
  namespace: gatekeeper-system
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "0"
spec:
  template:
    spec:
      containers:
        - name: sleeper
          image: busybox
          command: ["sh", "-c", "echo waiting for template... && sleep 10"]
      restartPolicy: Never
