apiVersion: batch/v1
kind: Job
metadata:
  name: kube-score
  namespace: security-scan
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: kube
      volumes:
        - name: output
          emptyDir: {}
      containers:
        - name: kube-score
          image: docker.io/zegl/kube-score:latest
          command:
            - /bin/sh
            - -c
            - |
              git clone --depth=1 https://github.com/learngryko/k8s_configs /repo && \
              find /repo \( -name '*.yaml' -o -name '*.yml' \) \
                -exec kube-score score {} --output-format json \; >> /output/report.json
          volumeMounts:
            - name: output
              mountPath: /output
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

        - name: sleeper
          image: busybox
          command: ["sh", "-c", "sleep 3600"]
          volumeMounts:
            - name: output
              mountPath: /output
