apiVersion: batch/v1
kind: Job
metadata:
  name: kube-score
  namespace: security-scan
  labels:
    job-name: kube-score
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 0 
  template:
    metadata:
      labels:
        job-name: kube-score
    spec:
      automountServiceAccountToken: false
      serviceAccountName: kube-bench
      restartPolicy: Never
      initContainers:
        - name: git-clone
          image: docker.io/bitnami/git:latest 
          command:
            - sh
            - -c
          args:
            - |
              git clone --depth=1 https://github.com/learngryko/k8s_configs /repo
          volumeMounts:
            - name: repo
              mountPath: /repo
          securityContext:
            readOnlyRootFilesystem: false 
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi

      containers:
        - name: kube-score
          image: docker.io/zegl/kube-score:latest
          command:
            - sh
            - -c
          args:
            - |
              score_out=$(find /repo/argocd/apps -name kustomization.yaml | xargs kube-score score --output-format=json)
              echo "$score_out" | tee /repo/score.json
          volumeMounts:
            - name: repo
              mountPath: /repo
          securityContext:
            readOnlyRootFilesystem: false 
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi

      volumes:
        - name: repo
          emptyDir: {}
