apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-score
  namespace: security-scan
spec:
  schedule: "@hourly"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        job-name: kube-score  # <-- KLUCZOWE
    spec:
      ttlSecondsAfterFinished: 300
      template:
        metadata:
          labels:
            job-name: kube-score  # <-- KLUCZOWE
        spec:
          automountServiceAccountToken: false
          serviceAccountName: kube-bench
          restartPolicy: Never
          containers:
            - name: git-clone
              image: docker.io/library/alpine:latest
              command: ["sh", "-c", "git clone --depth=1 https://github.com/learngryko/k8s_configs /repo"]
              volumeMounts:
                - name: repo
                  mountPath: /repo
              securityContext:
                readOnlyRootFilesystem: true
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 100m
                  memory: 128Mi

            - name: kube-score
              image: ghcr.io/zegl/kube-score:latest
              command: ["sh", "-c", "kube-score score /repo/argocd/apps/**/overlays/**/kustomization.yaml --output-format=json"]
              volumeMounts:
                - name: repo
                  mountPath: /repo
              securityContext:
                readOnlyRootFilesystem: true
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
          volumes:
            - name: repo
              emptyDir: {}
