apiVersion: batch/v1
kind: Job
metadata:
  name: kube-score
  namespace: security-scan
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: kube
      containers:
        - name: kube-score
          image: docker.io/zegl/kube-score:latest
          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache git && \
              git clone --depth=1 https://github.com/learngryko/k8s_configs /repo && \
              ulimit -n 4096 && \
              find /repo -name '*.yaml' -o -name '*.yml' > /tmp/yamls.txt && \
              jq -s '.' <(xargs -a /tmp/yamls.txt kube-score score --output-format json || true)
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
