apiVersion: batch/v1
kind: Job
metadata:
  name: kube-score
  namespace: security-scan
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: kube
      containers:
        - name: kube-score
          image: docker.io/bitnami/git:latest
          command:
            - /bin/sh
            - -c
            - |
              apt-get update && \
              apt-get install -y curl && \
              curl -L https://github.com/zegl/kube-score/releases/latest/download/kube-score-linux-amd64 -o /usr/local/bin/kube-score && \
              chmod +x /usr/local/bin/kube-score && \
              git clone --depth=1 https://github.com/learngryko/k8s_configs /repo && \
              kube-score score /repo --output-format json
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
