apiVersion: batch/v1
kind: Job
metadata:
  name: kube-score
  namespace: security-scan
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: kube
      containers:
        - name: kube-score
          image: docker.io/zegl/kube-score:latest
          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache git jq && \
              git clone --depth=1 https://github.com/learngryko/k8s_configs /repo && \
              ulimit -n 4096 && \
              TMPFILE=$(mktemp) && \
              find /repo -name '*.yaml' -o -name '*.yml' > "$TMPFILE" && \
              ( \
                while read -r file; do \
                  kube-score score "$file" --output-format json 2>/dev/null || true; \
                done < "$TMPFILE" \
              ) | grep -E '^\s*{' | jq -s '.'
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
