apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-score
  namespace: security-scan
spec:
  schedule: "@hourly"  # możesz zmienić np. na */10 * * * * dla co 10 minut
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        metadata:
          labels:
            job: kube-score
        spec:
          serviceAccountName: kube-bench
          restartPolicy: Never
          containers:
            - name: git-clone
              image: alpine/git
              command: ["sh", "-c", "git clone --depth=1 https://github.com/learngryko/k8s_configs /repo"]
              volumeMounts:
                - name: repo
                  mountPath: /repo

            - name: kube-score
              image: zegl/kube-score:latest
              command: ["sh", "-c", "kube-score score /repo/argocd/apps/**/overlays/**/kustomization.yaml --output-format=json"]
              volumeMounts:
                - name: repo
                  mountPath: /repo
                - name: output
                  mountPath: /output
          volumes:
            - name: repo
              emptyDir: {}
            - name: output
              emptyDir: {}
