apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedRepos
metadata:
  name: approved-registries
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
      - falco
  parameters:
    repos:
      - "docker.io/library/"
      - "docker.io/"
      - "ghcr.io/aquasecurity/"
      - "quay.io/argoproj/"
      - "mirror.gcr.io/aquasec/"
