apiVersion: v1
kind: Namespace
metadata:
  name: falco
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: falco
  namespace: kube-system
spec:
  chart: falco
  repo: https://falcosecurity.github.io/charts
  targetNamespace: falco
  version: 3.7.0
