apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8snohostpath
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/component: gatekeeper
    app.kubernetes.io/part-of: full-security
spec:
  crd:
    spec:
      names:
        kind: K8sNoHostPath
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8snohostpath
        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          volumeMount := input.review.object.spec.volumes[_]
          volumeMount.hostPath
          msg := "hostPath usage is not allowed"
        }
