kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: monitoring
  name: dev
rules:
- apiGroups: [""]
  resources: ["pods", "deployments", "configmaps", "secrets"]
  verbs: ["get", "list", "create", "update", "delete"]
