apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-viewer-binding
  namespace: prod
subjects:
- kind: User
  name: user-viewer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: viewer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-ops-binding
  namespace: prod
subjects:
- kind: User
  name: user-ops
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ops
  apiGroup: rbac.authorization.k8s.io
