kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: prod
  name: viewer
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: native-security
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
