kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: prod
  name: dev
labels:
  app.kubernetes.io/component: rbac
  app.kubernetes.io/part-of: native-security
rules:
- apiGroups: [""]
  resources: ["pods", "deployments", "configmaps", "secrets"]
  verbs: ["get", "list", "create", "update", "delete"]
