apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: global-default-security
spec:
  order: 1000
  selector: all()

  ingress:
    - action: Allow
      source:
        namespaceSelector: 'name == "argocd"'
      destination:
        namespaceSelector: 'name == "argocd"'

    - action: Allow
      source:
        namespaceSelector: 'name == "monitoring"'

    - action: Allow
      source:
        nets: ["192.168.88.0/24"]
      destination:
        namespaceSelector: 'name == "argocd"'

    - action: Deny
      source: {}

  egress:
    - action: Allow
      destination:
        namespaceSelector: 'name == "argocd"'

    - action: Allow
      destination:
        namespaceSelector: 'k8s.io/metadata.name == "kube-system"'
      protocol: UDP
      ports: [53]

    - action: Allow
      destination:
        namespaceSelector: 'name == "monitoring"'

    - action: Allow
      destination:
        namespaceSelector: 'k8s.io/metadata.name == "kube-system"'

    - action: Allow
      destination:
        nets: ["192.168.88.0/24"]
      protocol: TCP
      ports: [443]

    - action: Allow
      destination:
        nets: ["0.0.0.0/0"]
      protocol: TCP
      ports: [443]

    - action: Deny
      destination: {}
