apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: global-default-security
spec:
  # High order ensures namespace-scoped policies take precedence.
  order: 1000
  selector: all()

  ingress:
    # Allow all ingress traffic within the argocd namespace.
    - action: Allow
      source:
        namespaceSelector: 'name == "argocd"'
      destination:
        namespaceSelector: 'name == "argocd"'
      comment: Allow ingress within argocd namespace

    # Allow ingress traffic from the monitoring namespace (e.g., Prometheus scraping).
    - action: Allow
      source:
        namespaceSelector: 'name == "monitoring"'
      comment: Allow ingress from monitoring namespace

    # (Optional) Allow ingress from kube-dns if DNS discovery over TCP is needed.
    # - action: Allow
    #   source:
    #     namespaceSelector: 'k8s.io/metadata.name == "kube-system"'
    #     podSelector: 'k8s-app == "kube-dns"'
    #   protocol: TCP
    #   destination:
    #     ports: [53]
    #   comment: Allow ingress DNS over TCP

    # Deny all other ingress traffic.
    - action: Deny
      source: {}
      comment: Deny all other ingress

  egress:
    # Allow all egress traffic to the argocd namespace.
    - action: Allow
      destination:
        namespaceSelector: 'name == "argocd"'
      comment: Allow egress to argocd namespace

    # Allow egress DNS (UDP 53) to kube-dns in kube-system.
    - action: Allow
      destination:
        namespaceSelector: 'k8s.io/metadata.name == "kube-system"'
        podSelector: 'k8s-app == "kube-dns"'
        ports:
          - 53
      protocol: UDP
      comment: Allow egress DNS (UDP 53) to kube-dns

    # Allow all egress traffic to the monitoring namespace (logs, metrics).
    - action: Allow
      destination:
        namespaceSelector: 'name == "monitoring"'
      comment: Allow egress to monitoring namespace

    # Deny all other egress traffic.
    - action: Deny
      destination: {}
      comment: Deny all other egress
