apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: global-default-security
spec:
  order: 1000
  selector: all()

  ingress:
    # Allow all ingress traffic within the argocd namespace
    - action: Allow
      source:
        namespaceSelector: 'name == "argocd"'
      destination:
        namespaceSelector: 'name == "argocd"'

    # Allow ingress traffic from the monitoring namespace
    - action: Allow
      source:
        namespaceSelector: 'name == "monitoring"'

    # Allow ingress to argocd (GUI/API) from trusted network (np. Twoje biuro)
    - action: Allow
      source:
        nets: ["192.168.88.0/24"]       # <-- sieć biura (zmień na swoją!)
      destination:
        namespaceSelector: 'name == "argocd"'

    # Deny all other ingress traffic
    - action: Deny
      source: {}

  egress:
    # Allow all egress traffic to the argocd namespace
    - action: Allow
      destination:
        namespaceSelector: 'name == "argocd"'

    # Allow egress DNS (UDP 53) to kube-dns in kube-system
    - action: Allow
      destination:
        namespaceSelector: 'k8s.io/metadata.name == "kube-system"'
      protocol: UDP
      ports: [53]

    # Allow all egress traffic to the monitoring namespace
    - action: Allow
      destination:
        namespaceSelector: 'name == "monitoring"'

    # Allow egress to kube-system namespace (for API, csi, etc.)
    - action: Allow
      destination:
        namespaceSelector: 'k8s.io/metadata.name == "kube-system"'

    # Allow egress to Kubernetes API server subnet (przykład /24)
    - action: Allow
      destination:
        nets: ["192.168.88.0/24"]   # <-- sieć API servera (zmień na swoją!)
      protocol: TCP
      ports: [443]

    # Allow egress to public internet (np. GitHub)
    - action: Allow
      destination:
        nets: ["0.0.0.0/0"]
      protocol: TCP
      ports: [443]

    # Deny all other egress traffic
    - action: Deny
      destination: {}
