apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: global-default-security
spec:
  # Higher order means this policy will be evaluated after lower order policies.
  # Use a high order (e.g., 1000) to allow namespace-scoped policies to take precedence.
  order: 1000

  # Apply this policy to all pods in the cluster
  selector: all()

  ingress:
    # 1. Allow traffic from the monitoring namespace (e.g., Prometheus scraping)
    - action: Allow
      source:
        namespaceSelector: 'name == "monitoring"'
      comment: Allow all ingress from monitoring namespace (for scraping/metrics)
    
    # 2. (Optional) Allow ingress from kube-dns if you need DNS-based service discovery via TCP (rare)
    # - action: Allow
    #   source:
    #     namespaceSelector: ''
    #     podSelector: 'k8s-app == "kube-dns"'
    #   protocol: TCP
    #   destination:
    #     ports: [53]
    #   comment: Allow DNS over TCP (optional, usually UDP is enough)
    
    # 3. Default deny all other ingress traffic
    - action: Deny
      source: {}
      comment: Deny all other ingress

  egress:
    # 1. Allow DNS egress (UDP 53) to kube-dns pods in kube-system
    - action: Allow
      destination:
        namespaceSelector: 'k8s.io/metadata.name == "kube-system"'
        podSelector: 'k8s-app == "kube-dns"'
        ports:
          - 53
      protocol: UDP
      comment: Allow egress DNS (UDP 53) to kube-dns in kube-system

    # 2. Allow egress to monitoring namespace (for logs, metrics push)
    - action: Allow
      destination:
        namespaceSelector: 'name == "monitoring"'
      comment: Allow all egress to monitoring namespace (logs/metrics)

    # 3. Default deny all other egress traffic
    - action: Deny
      destination: {}
      comment: Deny all other egress
