apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: falco-security
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: falco
            path: overlays/full-security/falco/falco-core
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: security-project
      source:
        repoURL: https://github.com/learngryko/k8s_configs
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: falco
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
