apiVersion: v1
kind: Service
metadata:
  name: falco
  namespace: falco
  labels:
    app.kubernetes.io/name: falco
    app.kubernetes.io/instance: falco
    app.kubernetes.io/version: "0.40.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: falco
    app.kubernetes.io/instance: falco
  type: NodePort
  ports:
    - name: http
      port: 8765
      targetPort: 8765
      protocol: TCP
      nodePort: 30876
