apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
spec:
  project: default
  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: 0.40.0
    helm:
      values: |
        jsonOutput: true
        httpOutput:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true