apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: security-set
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/learngryko/k8s_configs
        revision: main
        directories:
          - path: argocd/apps/*
            exclude: ["*/disabled-*"]  # ← optional, for folder disables
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: security-project
      source:
        repoURL: https://github.com/learngryko/k8s_configs
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
