apiVersion: argoproj.io/v1alpha1
kind: Repository
metadata:
  name: aquasecurity
  namespace: argocd
spec:
  type: helm
  name: aquasecurity
  url: https://aquasecurity.github.io/helm-charts/
