apiVersion: v1
kind: ConfigMap
metadata:
  name: repositories
  namespace: argocd
data:
  aquasecurity-helm-repo: |
    url: https://aquasecurity.github.io/helm-charts/
    name: aquasecurity
    type: helm
