apiVersion: v1
kind: Secret
metadata:
  name: aquasecurity-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: aquasecurity
  url: https://aquasecurity.github.io/helm-charts/
