apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-viewer-binding
  namespace: monitoring
subjects:
- kind: User
  name: user-viewer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: viewer
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitoring-ops-binding
  namespace: monitoring
subjects:
- kind: User
  name: user-ops
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ops
  apiGroup: rbac.authorization.k8s.io
