kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: monitoring
  name: ops
labels:
  app.kubernetes.io/component: rbac
  app.kubernetes.io/part-of: native-security
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
