apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd  # ArgoCD manages the app from here
spec:
  project: security-project
  source:
    repoURL: https://aquasecurity.github.io/helm-charts/
    chart: trivy-operator
    targetRevision: 0.28.1
    helm:
      releaseName: trivy-operator
      values: |
        trivy:
          ignoreUnfixed: true
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        podSecurityContext:
          readOnlyRootFilesystem: true
        automountServiceAccountToken: false
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
