apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  project: security-project
  source:
    repoURL: https://aquasecurity.github.io/helm-charts
    chart: trivy-operator
    targetRevision: 0.28.1
    helm:
      releaseName: trivy-operator
      values: |
        automountServiceAccountToken: true
        trivy:
          ignoreUnfixed: true
        operator:
          image:
            registry: ghcr.io
            repository: aquasecurity/trivy-operator
            tag: 0.28.1
          targetNamespaces: "all"
          excludeNamespaces: ""
          targetWorkloads: "pod,replicaset,replicationcontroller,statefulset,daemonset,cronjob,job"
          configAuditScannerEnabled: true
          rbacAssessmentScannerEnabled: true
        cronScan:
          enabled: true
          scanOnlyCurrentRevisions: false
          schedule: "0 * * * *"
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
