apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy-operator
  template:
    metadata:
      labels:
        app: trivy-operator
    spec:
      containers:
        - name: trivy-operator
          image: ghcr.io/aquasecurity/trivy-operator:0.28.1
          args:
            - "--trivy.ignore-unfixed=true"
