apiVersion: v1
kind: Namespace
metadata:
  name: calico-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    app.kubernetes.io/component: calico
    app.kubernetes.io/part-of: calico-network
  