apiVersion: v1
kind: Namespace
metadata:
  name: falco-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    app.kubernetes.io/component: falco
    app.kubernetes.io/part-of: falco-network
  