apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: full-security
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: fullserurity-base
            path: overlays/full-security
            wave: "0"
          - name: gatekeeper-core
            path: overlays/full-security/gatekeeper/gatekeeper-core
            namespace: gatekeeper-system
            wave: "1"
          - name: gatekeeper-policies
            path: overlays/full-security/gatekeeper/gatekeeper-policies
            namespace: gatekeeper-system
            wave: "2"
          - name: falco
            path: overlays/full-security/falco
            namespace: falco
            wave: "3"
          - name: trivy-operator
            namespace: trivy-system
            wave: "4"
            source:
              repoURL: https://aquasecurity.github.io/helm-charts/
              chart: trivy-operator
              targetRevision: "0.28.1"
              helm:
                releaseName: trivy-operator
                values: |
                  trivy:
                    ignoreUnfixed: true
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: security-project
      source:
        repoURL: https://github.com/learngryko/k8s_configs
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
