apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: full-security
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: fullserurity-base
            path: overlays/full-security
            wave: "0"
          - name: gatekeeper-core
            path: overlays/full-security/gatekeeper/gatekeeper-core
            namespace: gatekeeper-system
            wave: "1"
          - name: gatekeeper-policies
            path: overlays/full-security/gatekeeper/gatekeeper-policies
            namespace: gatekeeper-system
            wave: "2"
          - name: falco
            path: overlays/full-security/falco
            namespace: falco
            wave: "3"
          - name: trivy-operator
            chart: trivy-operator
            repoURL: https://aquasecurity.github.io/helm-charts/
            targetRevision: latest
            namespace: trivy-system
            wave: "4"
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: security-project
      source:
        repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        targetRevision: '{{targetRevision}}'
        helm:
          releaseName: trivy-operator
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
