resources:
  - ../../base

  #RBAC
  - rbac/dev/role-viewer.yaml
  - rbac/dev/role-dev.yaml
  - rbac/dev/role-ops.yaml
  - rbac/dev/bindings.yaml
  - rbac/prod/role-viewer.yaml
  - rbac/prod/role-dev.yaml
  - rbac/prod/role-ops.yaml
  - rbac/prod/bindings.yaml
  - rbac/monitoring/role-viewer.yaml
  - rbac/monitoring/role-dev.yaml
  - rbac/monitoring/role-ops.yaml
  - rbac/monitoring/bindings.yaml
  
patchesStrategicMerge:
  #PSA
  - namespace-patches/prod.yaml
  - namespace-patches/dev.yaml
  - namespace-patches/monitoring.yaml
